//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BECOSOFT.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BECOSOFT.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching is disabled.
        /// </summary>
        public static string Caching_CachingDisabledException {
            get {
                return ResourceManager.GetString("Caching_CachingDisabledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is empty.
        /// </summary>
        public static string Email_Validation_Empty {
            get {
                return ResourceManager.GetString("Email_Validation_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is too long (max. {0} characters).
        /// </summary>
        public static string Email_Validation_Length {
            get {
                return ResourceManager.GetString("Email_Validation_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is malformed.
        /// </summary>
        public static string Email_Validation_Malformed {
            get {
                return ResourceManager.GetString("Email_Validation_Malformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the database..
        /// </summary>
        public static string Error_Connection {
            get {
                return ResourceManager.GetString("Error_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection..
        /// </summary>
        public static string Error_Connection_Invalid {
            get {
                return ResourceManager.GetString("Error_Connection_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result object not filled since no columns are present..
        /// </summary>
        public static string Error_ConvertEntity_NeverSet {
            get {
                return ResourceManager.GetString("Error_ConvertEntity_NeverSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defining type does not exist..
        /// </summary>
        public static string Error_DefiningType_NonExistent {
            get {
                return ResourceManager.GetString("Error_DefiningType_NonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected type of TableConsumingEntity&lt;T&gt; found..
        /// </summary>
        public static string Error_InvalidType_TableConsuming {
            get {
                return ResourceManager.GetString("Error_InvalidType_TableConsuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table part is missing..
        /// </summary>
        public static string Error_MissingTablePart {
            get {
                return ResourceManager.GetString("Error_MissingTablePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name is not defined..
        /// </summary>
        public static string Error_TableName_Undefined {
            get {
                return ResourceManager.GetString("Error_TableName_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 translation is required..
        /// </summary>
        public static string General_Translations_AtleastOneRequired {
            get {
                return ResourceManager.GetString("General_Translations_AtleastOneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the languages is duplicated..
        /// </summary>
        public static string General_Translations_DuplicateLanguage {
            get {
                return ResourceManager.GetString("General_Translations_DuplicateLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is missing..
        /// </summary>
        public static string General_Translations_Language_Missing {
            get {
                return ResourceManager.GetString("General_Translations_Language_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language is non existent..
        /// </summary>
        public static string General_Translations_Language_NonExistent {
            get {
                return ResourceManager.GetString("General_Translations_Language_NonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not linked to a(-n) {1}.
        /// </summary>
        public static string General_Validation_LinkedEntity_Missing {
            get {
                return ResourceManager.GetString("General_Validation_LinkedEntity_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is linked to a non-existent {1}.
        /// </summary>
        public static string General_Validation_LinkedEntity_NonExistent {
            get {
                return ResourceManager.GetString("General_Validation_LinkedEntity_NonExistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be inserted.
        /// </summary>
        public static string General_Validation_NonInsertableProperty {
            get {
                return ResourceManager.GetString("General_Validation_NonInsertableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property cannot be updated.
        /// </summary>
        public static string General_Validation_NonUpdateableProperty {
            get {
                return ResourceManager.GetString("General_Validation_NonUpdateableProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more errors are present..
        /// </summary>
        public static string General_Validation_OneOrMoreErrors {
            get {
                return ResourceManager.GetString("General_Validation_OneOrMoreErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string Operator_And {
            get {
                return ResourceManager.GetString("Operator_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Operator_Or {
            get {
                return ResourceManager.GetString("Operator_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; does not exist on type &quot;{1}&quot;..
        /// </summary>
        public static string PropertyType_InvalidArgument {
            get {
                return ResourceManager.GetString("PropertyType_InvalidArgument", resourceCulture);
            }
        }
    }
}
