//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BECOSOFT.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BECOSOFT.Web.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional: additional information about the content. If you would like to have specific items offered, please mention this here..
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional keywords.
        /// </summary>
        public static string AdditionalKeywords {
            get {
                return ResourceManager.GetString("AdditionalKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI text generator.
        /// </summary>
        public static string AIGenerator {
            get {
                return ResourceManager.GetString("AIGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images - Bulk upload.
        /// </summary>
        public static string ArticleImage_BulkUpload {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following images already existed in the upload and have not been added again:.
        /// </summary>
        public static string ArticleImage_BulkUpload_AlreadyUploadedAlert {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_AlreadyUploadedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm images.
        /// </summary>
        public static string ArticleImage_BulkUpload_ConfirmImages {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_ConfirmImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm settings.
        /// </summary>
        public static string ArticleImage_BulkUpload_ConfirmSettings {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_ConfirmSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must confirm the settings before images can be added..
        /// </summary>
        public static string ArticleImage_BulkUpload_ConfirmSettingsAlert {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_ConfirmSettingsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading response....
        /// </summary>
        public static string ArticleImage_BulkUpload_DownloadingResponse {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_DownloadingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated position.
        /// </summary>
        public static string ArticleImage_BulkUpload_EstimatedPosition {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_EstimatedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching information.
        /// </summary>
        public static string ArticleImage_BulkUpload_FetchingInformation {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_FetchingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matched article.
        /// </summary>
        public static string ArticleImage_BulkUpload_MatchedArticle {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_MatchedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed position is {0}.
        /// </summary>
        public static string ArticleImage_BulkUpload_MaximumPosition {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_MaximumPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total file size ({0}GB) exceeds {1}GB, please choose fewer images..
        /// </summary>
        public static string ArticleImage_BulkUpload_MaximumSize {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_MaximumSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing images....
        /// </summary>
        public static string ArticleImage_BulkUpload_ParsingImages {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_ParsingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left.
        /// </summary>
        public static string ArticleImage_BulkUpload_RotateLeft {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right.
        /// </summary>
        public static string ArticleImage_BulkUpload_RotateRight {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved position.
        /// </summary>
        public static string ArticleImage_BulkUpload_SavedPosition {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_SavedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save images.
        /// </summary>
        public static string ArticleImage_BulkUpload_SaveImages {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_SaveImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving images.
        /// </summary>
        public static string ArticleImage_BulkUpload_SavingImages {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_SavingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload settings.
        /// </summary>
        public static string ArticleImage_BulkUpload_Settings {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new upload.
        /// </summary>
        public static string ArticleImage_BulkUpload_StartNewUpload {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_StartNewUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add images after uploads have been confirmed..
        /// </summary>
        public static string ArticleImage_BulkUpload_UploadConfirmedAlert {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_UploadConfirmedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload images.
        /// </summary>
        public static string ArticleImage_BulkUpload_UploadImages {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading data....
        /// </summary>
        public static string ArticleImage_BulkUpload_UploadingData {
            get {
                return ResourceManager.GetString("ArticleImage_BulkUpload_UploadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ArticleImage_Continue {
            get {
                return ResourceManager.GetString("ArticleImage_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that you are uploading an image with low quality. The width of this image is.
        /// </summary>
        public static string ArticleImage_CurrentWidth {
            get {
                return ResourceManager.GetString("ArticleImage_CurrentWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select other image.
        /// </summary>
        public static string ArticleImage_SelectOtherImage {
            get {
                return ResourceManager.GetString("ArticleImage_SelectOtherImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload images.
        /// </summary>
        public static string ArticleImage_UploadImages {
            get {
                return ResourceManager.GetString("ArticleImage_UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is strongly recommended that you upload images at least 750px wide for proper display..
        /// </summary>
        public static string ArticleImage_WarningImageToSmall {
            get {
                return ResourceManager.GetString("ArticleImage_WarningImageToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string ArticleInformation_BingSearchResult_Download {
            get {
                return ResourceManager.GetString("ArticleInformation_BingSearchResult_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on Bing.
        /// </summary>
        public static string ArticleInformation_SearchOnBing {
            get {
                return ResourceManager.GetString("ArticleInformation_SearchOnBing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search images online.
        /// </summary>
        public static string ArticleInformation_SearchOnline {
            get {
                return ResourceManager.GetString("ArticleInformation_SearchOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe in maximum 25 words what the content should be about..
        /// </summary>
        public static string DescribeContent {
            get {
                return ResourceManager.GetString("DescribeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download order confirmation.
        /// </summary>
        public static string DownloadOrderConfirmation {
            get {
                return ResourceManager.GetString("DownloadOrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail order confirmation.
        /// </summary>
        public static string EmailOrderConfirmation {
            get {
                return ResourceManager.GetString("EmailOrderConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will try to fix this as soon as possible..
        /// </summary>
        public static string Error_FixAsSoonAsPossible {
            get {
                return ResourceManager.GetString("Error_FixAsSoonAsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        public static string Error_GoBack {
            get {
                return ResourceManager.GetString("Error_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL, request cannot be processed..
        /// </summary>
        public static string Error_InvalidUrlError {
            get {
                return ResourceManager.GetString("Error_InvalidUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page you are trying to visit, does not exist..
        /// </summary>
        public static string Error_NotFound {
            get {
                return ResourceManager.GetString("Error_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page does not exist..
        /// </summary>
        public static string Error_NotFound_Title {
            get {
                return ResourceManager.GetString("Error_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, looks like something went wrong..
        /// </summary>
        public static string Error_Oops {
            get {
                return ResourceManager.GetString("Error_Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Error_Retry {
            get {
                return ResourceManager.GetString("Error_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important keywords.
        /// </summary>
        public static string ImportantKeywords {
            get {
                return ResourceManager.GetString("ImportantKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key keywords the content should contain (SEO).
        /// </summary>
        public static string KeywordsContentMustContain {
            get {
                return ResourceManager.GetString("KeywordsContentMustContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords that must also be incorporated into the content.
        /// </summary>
        public static string KeywordsInContent {
            get {
                return ResourceManager.GetString("KeywordsInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add filtered contacts.
        /// </summary>
        public static string WebsiteUser_AddFilteredContacts {
            get {
                return ResourceManager.GetString("WebsiteUser_AddFilteredContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove filtered contacts.
        /// </summary>
        public static string WebsiteUser_RemoveFilteredContacts {
            get {
                return ResourceManager.GetString("WebsiteUser_RemoveFilteredContacts", resourceCulture);
            }
        }
    }
}
