//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BECOSOFT.Utilities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BECOSOFT.Utilities.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string DayOfWeek_Friday {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string DayOfWeek_Friday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Friday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string DayOfWeek_Monday {
            get {
                return ResourceManager.GetString("DayOfWeek_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string DayOfWeek_Monday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Monday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string DayOfWeek_Saturday {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string DayOfWeek_Saturday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Saturday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string DayOfWeek_Sunday {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string DayOfWeek_Sunday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Sunday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string DayOfWeek_Thursday {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string DayOfWeek_Thursday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Thursday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string DayOfWeek_Tuesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string DayOfWeek_Tuesday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Tuesday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string DayOfWeek_Wednesday {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string DayOfWeek_Wednesday_Short {
            get {
                return ResourceManager.GetString("DayOfWeek_Wednesday_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string FilterOperator_Contains {
            get {
                return ResourceManager.GetString("FilterOperator_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string FilterOperator_EndsWith {
            get {
                return ResourceManager.GetString("FilterOperator_EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        public static string FilterOperator_EqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string FilterOperator_GreaterThan {
            get {
                return ResourceManager.GetString("FilterOperator_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal to.
        /// </summary>
        public static string FilterOperator_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is equal to.
        /// </summary>
        public static string FilterOperator_In {
            get {
                return ResourceManager.GetString("FilterOperator_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is.
        /// </summary>
        public static string FilterOperator_Is {
            get {
                return ResourceManager.GetString("FilterOperator_Is", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length equal to.
        /// </summary>
        public static string FilterOperator_LengthEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_LengthEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length greater than.
        /// </summary>
        public static string FilterOperator_LengthGreaterThan {
            get {
                return ResourceManager.GetString("FilterOperator_LengthGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length greater than or equal to.
        /// </summary>
        public static string FilterOperator_LengthGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_LengthGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length less than.
        /// </summary>
        public static string FilterOperator_LengthLessThan {
            get {
                return ResourceManager.GetString("FilterOperator_LengthLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length less than or equal to.
        /// </summary>
        public static string FilterOperator_LengthLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_LengthLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length not equal to.
        /// </summary>
        public static string FilterOperator_LengthNotEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_LengthNotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        public static string FilterOperator_LessThan {
            get {
                return ResourceManager.GetString("FilterOperator_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equal to.
        /// </summary>
        public static string FilterOperator_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not contains.
        /// </summary>
        public static string FilterOperator_NotContains {
            get {
                return ResourceManager.GetString("FilterOperator_NotContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        public static string FilterOperator_NotEqualTo {
            get {
                return ResourceManager.GetString("FilterOperator_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        public static string FilterOperator_NotIn {
            get {
                return ResourceManager.GetString("FilterOperator_NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string FilterOperator_StartsWith {
            get {
                return ResourceManager.GetString("FilterOperator_StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string General_False {
            get {
                return ResourceManager.GetString("General_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string General_True {
            get {
                return ResourceManager.GetString("General_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of &quot;To&quot; exceeds the length of the mask..
        /// </summary>
        public static string Mask_ToExceedsMaskLength {
            get {
                return ResourceManager.GetString("Mask_ToExceedsMaskLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        public static string Measurement_Gross {
            get {
                return ResourceManager.GetString("Measurement_Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Measurement_Height {
            get {
                return ResourceManager.GetString("Measurement_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.
        /// </summary>
        public static string Measurement_Height_Abbreviation {
            get {
                return ResourceManager.GetString("Measurement_Height_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Measurement_Length {
            get {
                return ResourceManager.GetString("Measurement_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string Measurement_Length_Abbreviation {
            get {
                return ResourceManager.GetString("Measurement_Length_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        public static string Measurement_Net {
            get {
                return ResourceManager.GetString("Measurement_Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare.
        /// </summary>
        public static string Measurement_Tare {
            get {
                return ResourceManager.GetString("Measurement_Tare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Measurement_Weight {
            get {
                return ResourceManager.GetString("Measurement_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Measurement_Width {
            get {
                return ResourceManager.GetString("Measurement_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Measurement_Width_Abbreviation {
            get {
                return ResourceManager.GetString("Measurement_Width_Abbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimetre.
        /// </summary>
        public static string MetricLengthUnit_Centimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Centimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic centimetre.
        /// </summary>
        public static string MetricLengthUnit_CubicCentimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicCentimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic decametre.
        /// </summary>
        public static string MetricLengthUnit_CubicDecametre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicDecametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic decimetre.
        /// </summary>
        public static string MetricLengthUnit_CubicDecimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicDecimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic hectometre.
        /// </summary>
        public static string MetricLengthUnit_CubicHectometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicHectometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic kilometre.
        /// </summary>
        public static string MetricLengthUnit_CubicKilometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicKilometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic metre.
        /// </summary>
        public static string MetricLengthUnit_CubicMetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cubic millimetre.
        /// </summary>
        public static string MetricLengthUnit_CubicMillimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_CubicMillimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decametre.
        /// </summary>
        public static string MetricLengthUnit_Decametre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Decametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimetre.
        /// </summary>
        public static string MetricLengthUnit_Decimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Decimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectometre.
        /// </summary>
        public static string MetricLengthUnit_Hectometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Hectometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometre.
        /// </summary>
        public static string MetricLengthUnit_Kilometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Kilometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metre.
        /// </summary>
        public static string MetricLengthUnit_Metre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Metre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micrometre.
        /// </summary>
        public static string MetricLengthUnit_Micrometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Micrometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimetre.
        /// </summary>
        public static string MetricLengthUnit_Millimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Millimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanometre.
        /// </summary>
        public static string MetricLengthUnit_Nanometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Nanometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picometre.
        /// </summary>
        public static string MetricLengthUnit_Picometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_Picometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square centimetre.
        /// </summary>
        public static string MetricLengthUnit_SquareCentimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareCentimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square decametre.
        /// </summary>
        public static string MetricLengthUnit_SquareDecametre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareDecametre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square decimetre.
        /// </summary>
        public static string MetricLengthUnit_SquareDecimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareDecimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square hectometre.
        /// </summary>
        public static string MetricLengthUnit_SquareHectometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareHectometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square kilometre.
        /// </summary>
        public static string MetricLengthUnit_SquareKilometre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareKilometre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square metre.
        /// </summary>
        public static string MetricLengthUnit_SquareMetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareMetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square millimetre.
        /// </summary>
        public static string MetricLengthUnit_SquareMillimetre {
            get {
                return ResourceManager.GetString("MetricLengthUnit_SquareMillimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decagram.
        /// </summary>
        public static string MetricWeightUnit_Decagram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Decagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gram.
        /// </summary>
        public static string MetricWeightUnit_Gram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Gram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hectogram.
        /// </summary>
        public static string MetricWeightUnit_Hectogram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Hectogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram.
        /// </summary>
        public static string MetricWeightUnit_Kilogram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Kilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microgram.
        /// </summary>
        public static string MetricWeightUnit_Microgram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Microgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milligram.
        /// </summary>
        public static string MetricWeightUnit_Milligram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Milligram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nanogram.
        /// </summary>
        public static string MetricWeightUnit_Nanogram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Nanogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picogram.
        /// </summary>
        public static string MetricWeightUnit_Picogram {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Picogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tonne.
        /// </summary>
        public static string MetricWeightUnit_Tonne {
            get {
                return ResourceManager.GetString("MetricWeightUnit_Tonne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Month_April {
            get {
                return ResourceManager.GetString("Month_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augustus.
        /// </summary>
        public static string Month_August {
            get {
                return ResourceManager.GetString("Month_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Month_December {
            get {
                return ResourceManager.GetString("Month_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Month_February {
            get {
                return ResourceManager.GetString("Month_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Month_January {
            get {
                return ResourceManager.GetString("Month_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Month_July {
            get {
                return ResourceManager.GetString("Month_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Month_June {
            get {
                return ResourceManager.GetString("Month_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Month_March {
            get {
                return ResourceManager.GetString("Month_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Month_November {
            get {
                return ResourceManager.GetString("Month_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Month_October {
            get {
                return ResourceManager.GetString("Month_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Month_September {
            get {
                return ResourceManager.GetString("Month_September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string OffsetType_Day {
            get {
                return ResourceManager.GetString("OffsetType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string OffsetType_Month {
            get {
                return ResourceManager.GetString("OffsetType_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string OffsetType_None {
            get {
                return ResourceManager.GetString("OffsetType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string OffsetType_Year {
            get {
                return ResourceManager.GetString("OffsetType_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string Orientation_Landscape {
            get {
                return ResourceManager.GetString("Orientation_Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string Orientation_Portrait {
            get {
                return ResourceManager.GetString("Orientation_Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheapest.
        /// </summary>
        public static string PromotionActionArticleType_Cheapest {
            get {
                return ResourceManager.GetString("PromotionActionArticleType_Cheapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most expensive.
        /// </summary>
        public static string PromotionActionArticleType_MostExpensive {
            get {
                return ResourceManager.GetString("PromotionActionArticleType_MostExpensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most expensive line.
        /// </summary>
        public static string PromotionActionArticleType_MostExpensiveLine {
            get {
                return ResourceManager.GetString("PromotionActionArticleType_MostExpensiveLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most expensive line (consolidated).
        /// </summary>
        public static string PromotionActionArticleType_MostExpensiveLineConsolidated {
            get {
                return ResourceManager.GetString("PromotionActionArticleType_MostExpensiveLineConsolidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All articles.
        /// </summary>
        public static string PromotionConditionType_AllArticles {
            get {
                return ResourceManager.GetString("PromotionConditionType_AllArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article ID.
        /// </summary>
        public static string PromotionConditionType_ArticleID {
            get {
                return ResourceManager.GetString("PromotionConditionType_ArticleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string PromotionConditionType_Brand {
            get {
                return ResourceManager.GetString("PromotionConditionType_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand value.
        /// </summary>
        public static string PromotionConditionType_BrandValue {
            get {
                return ResourceManager.GetString("PromotionConditionType_BrandValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount group.
        /// </summary>
        public static string PromotionConditionType_DiscountGroup {
            get {
                return ResourceManager.GetString("PromotionConditionType_DiscountGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document value.
        /// </summary>
        public static string PromotionConditionType_DocumentValue {
            get {
                return ResourceManager.GetString("PromotionConditionType_DocumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document value (excluding other promotions).
        /// </summary>
        public static string PromotionConditionType_DocumentValueExcludingOtherPromotion {
            get {
                return ResourceManager.GetString("PromotionConditionType_DocumentValueExcludingOtherPromotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection.
        /// </summary>
        public static string PromotionConditionType_FashionCollection {
            get {
                return ResourceManager.GetString("PromotionConditionType_FashionCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string PromotionConditionType_FashionColor {
            get {
                return ResourceManager.GetString("PromotionConditionType_FashionColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fabric.
        /// </summary>
        public static string PromotionConditionType_FashionFabric {
            get {
                return ResourceManager.GetString("PromotionConditionType_FashionFabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string PromotionConditionType_Group {
            get {
                return ResourceManager.GetString("PromotionConditionType_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size bar article.
        /// </summary>
        public static string PromotionConditionType_Matrix {
            get {
                return ResourceManager.GetString("PromotionConditionType_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string PromotionConditionType_None {
            get {
                return ResourceManager.GetString("PromotionConditionType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product value.
        /// </summary>
        public static string PromotionConditionType_ProductValue {
            get {
                return ResourceManager.GetString("PromotionConditionType_ProductValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion article filter.
        /// </summary>
        public static string PromotionConditionType_PromotionArticleFilter {
            get {
                return ResourceManager.GetString("PromotionConditionType_PromotionArticleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string PromotionConditionType_Season {
            get {
                return ResourceManager.GetString("PromotionConditionType_Season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        public static string PromotionConditionType_Tag {
            get {
                return ResourceManager.GetString("PromotionConditionType_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type (article).
        /// </summary>
        public static string PromotionConditionType_Type {
            get {
                return ResourceManager.GetString("PromotionConditionType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string PromotionConditionType_Weight {
            get {
                return ResourceManager.GetString("PromotionConditionType_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different from.
        /// </summary>
        public static string PromotionTypeOperator_DifferentFrom {
            get {
                return ResourceManager.GetString("PromotionTypeOperator_DifferentFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        public static string PromotionTypeOperator_EqualTo {
            get {
                return ResourceManager.GetString("PromotionTypeOperator_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of month.
        /// </summary>
        public static string RelativeDateConstant_EndOfMonth {
            get {
                return ResourceManager.GetString("RelativeDateConstant_EndOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of year.
        /// </summary>
        public static string RelativeDateConstant_EndOfYear {
            get {
                return ResourceManager.GetString("RelativeDateConstant_EndOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        public static string RelativeDateConstant_Now {
            get {
                return ResourceManager.GetString("RelativeDateConstant_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of month.
        /// </summary>
        public static string RelativeDateConstant_StartOfMonth {
            get {
                return ResourceManager.GetString("RelativeDateConstant_StartOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of year.
        /// </summary>
        public static string RelativeDateConstant_StartOfYear {
            get {
                return ResourceManager.GetString("RelativeDateConstant_StartOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string RelativeDateConstant_Today {
            get {
                return ResourceManager.GetString("RelativeDateConstant_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string RelativeDateConstant_Unknown {
            get {
                return ResourceManager.GetString("RelativeDateConstant_Unknown", resourceCulture);
            }
        }
    }
}
